UPDATE works SET kind='novella' WHERE id='blackwood::the-willows';
UPDATE works SET desc='Novella; first collected in The Listener and Other Stories (1907); widely anthologized.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='blackwood::the-willows' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='blackwood::the-wendigo';
UPDATE works SET desc='Novella; in The Lost Valley and Other Stories (1910).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='blackwood::the-wendigo' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='story' WHERE id='leiber::smoke-ghost';
UPDATE works SET desc='Short story; collected in Night''s Black Agents (1947).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='leiber::smoke-ghost' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='jackson::the-summer-people';
UPDATE works SET desc='Short story; collected in Come Along with Me; also in the Dark Tales selection.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='jackson::the-summer-people' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='ewers::the-spider';
UPDATE works SET desc='Short story; widely anthologized in English.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='ewers::the-spider' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='novella' WHERE id='dumaurier::don-t-look-now';
UPDATE works SET desc='Novella; in Not After Midnight (1971), later retitled Don''t Look Now and Other Stories.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='dumaurier::don-t-look-now' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='dumaurier::the-birds';
UPDATE works SET desc='Novella; in The Apple Tree (1952).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='dumaurier::the-birds' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='machen::the-great-god-pan';
UPDATE works SET desc='Novella; first published in book form with The Inmost Light (1894).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='machen::the-great-god-pan' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='story' WHERE id='mrjames::oh-whistle-and-i-ll-come-to-you';
UPDATE works SET desc='Short story; in Ghost Stories of an Antiquary (1904).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='mrjames::oh-whistle-and-i-ll-come-to-you' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='novella' WHERE id='maupassant::the-horla';
UPDATE works SET desc='Novella; widely anthologized.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='maupassant::the-horla' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='aktolstoy::the-family-of-the-vourdalak';
UPDATE works SET desc='Novella; widely anthologized.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='aktolstoy::the-family-of-the-vourdalak' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='story' WHERE id='gilman::the-yellow-wallpaper';
UPDATE works SET desc='Short story; widely anthologized.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='gilman::the-yellow-wallpaper' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='rehoward::pigeons-from-hell';
UPDATE works SET desc='Short story; in the posthumous collection Pigeons from Hell (1976).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='rehoward::pigeons-from-hell' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='bierce::the-death-of-halpin-frayser';
UPDATE works SET desc='Short story; in Can Such Things Be? (1893).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='bierce::the-death-of-halpin-frayser' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='hawthorne::young-goodman-brown';
UPDATE works SET desc='Short story; in Mosses from an Old Manse (1846).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='hawthorne::young-goodman-brown' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='gautier::la-morte-amoureuse';
UPDATE works SET desc='Short story; widely anthologized in English as Clarimonde.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='gautier::la-morte-amoureuse' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='novella' WHERE id='gogol::viy';
UPDATE works SET desc='Novella; in Mirgorod (1835).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='gogol::viy' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='story' WHERE id='gogol::the-nose';
UPDATE works SET desc='Short story; one of the Petersburg Tales.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='gogol::the-nose' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='ellison::the-deathbird';
UPDATE works SET desc='Short story; in Deathbird Stories (1975).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='ellison::the-deathbird' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='ellison::i-have-no-mouth-and-i-must-scream';
UPDATE works SET desc='Short story; title story of the 1967 collection.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='ellison::i-have-no-mouth-and-i-must-scream' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='oates::where-are-you-going-where-have-you-been';
UPDATE works SET desc='Short story; in The Wheel of Love (1970); widely anthologized.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='oates::where-are-you-going-where-have-you-been' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='akutagawa::rash-mon';
UPDATE works SET desc='Short story; in Rashomon and Seventeen Other Stories (Penguin Classics).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='akutagawa::rash-mon' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='akutagawa::hell-screen';
UPDATE works SET desc='Short story; in Rashomon and Seventeen Other Stories (Penguin Classics).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='akutagawa::hell-screen' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='ranpo::the-human-chair';
UPDATE works SET desc='Short story; in Japanese Tales of Mystery and Imagination (1956).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='ranpo::the-human-chair' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='ranpo::the-caterpillar';
UPDATE works SET desc='Short story; in Japanese Tales of Mystery and Imagination (1956).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='ranpo::the-caterpillar' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='hoffmann::the-sandman';
UPDATE works SET desc='Short story; from the Night Pieces (1816); in the Penguin Tales of Hoffmann.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='hoffmann::the-sandman' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='novella' WHERE id='lefanu::carmilla';
UPDATE works SET desc='Novella; in In a Glass Darkly (1872).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='lefanu::carmilla' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='story' WHERE id='lefanu::green-tea';
UPDATE works SET desc='Short story; in In a Glass Darkly (1872).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='lefanu::green-tea' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='delamare::seaton-s-aunt';
UPDATE works SET desc='Short story; in The Riddle and Other Stories (1923).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='delamare::seaton-s-aunt' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='benson::the-room-in-the-tower';
UPDATE works SET desc='Short story; title story of the 1912 collection.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='benson::the-room-in-the-tower' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='novella' WHERE id='oliphant::the-open-door';
UPDATE works SET desc='Novella; widely anthologized.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='oliphant::the-open-door' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='tuttle::my-death';
UPDATE works SET desc='Novella; reissued standalone by NYRB Classics (2023).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='tuttle::my-death' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='fuentes::aura';
UPDATE works SET desc='Novella; published standalone.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='fuentes::aura' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='lovecraft::the-shadow-over-innsmouth';
UPDATE works SET desc='Novella; widely collected.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='lovecraft::the-shadow-over-innsmouth' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='lovecraft::at-the-mountains-of-madness';
UPDATE works SET desc='Novella; widely collected.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='lovecraft::at-the-mountains-of-madness' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='novella' WHERE id='kyoka::the-holy-man-of-mount-koya';
UPDATE works SET desc='Novella; in Japanese Gothic Tales (trans. Inouye).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='kyoka::the-holy-man-of-mount-koya' AND desc NOT LIKE 'Novella%';
UPDATE works SET kind='story' WHERE id='connell::the-most-dangerous-game';
UPDATE works SET desc='Short story; widely anthologized.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='connell::the-most-dangerous-game' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='beaumont::perchance-to-dream';
UPDATE works SET desc='Short story; title story of the Penguin Classics collection.' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='beaumont::perchance-to-dream' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='story' WHERE id='cas::the-dark-eidolon';
UPDATE works SET desc='Short story; in The Dark Eidolon and Other Fantasies (Penguin Classics).' || CASE WHEN desc='' OR desc IS NULL THEN '' ELSE ' ' || desc END WHERE id='cas::the-dark-eidolon' AND desc NOT LIKE 'Short story%';
UPDATE works SET kind='collection' WHERE id='wagner::why-not-you-and-i';